//Villes les plus grandes de france
export const POPULAR_CITIES = [
  'Paris',
  'Marseille',
  'Lyon',
  'Toulouse',
  'Nice',
  'Nantes',
  'Montpellier',
  'Strasbourg',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Saint-Étienne',
  'Toulon',
  'Le Havre',
  'Grenoble',
  'Dijon',
  'Angers',
  'Nîmes',
  'Saint-Denis',
  'Villeurbanne',
  'Clermont-Ferrand',
];
