//Table des codes renvoyé par l'api, qui donne le temps associés aux codes des champs weather des objets forecast.
//https://api.meteo-concept.com/documentation#code-temps
export const WEATHER_CODES = {
  0: 'Soleil',
  1: 'Peu nuageux',
  2: 'Ciel voilé',
  3: 'Nuageux',
  4: 'Très nuageux',
  5: 'Couvert',
  6: 'Brouillard',
  7: 'Brouillard givrant',
  10: 'Pluie faible',
  11: 'Pluie modérée',
  12: 'Pluie forte',
  13: 'Pluie faible verglaçante',
  14: 'Pluie modérée verglaçante',
  15: 'Pluie forte verglaçante',
  16: 'Bruine',
  20: 'Neige faible',
  21: 'Neige modérée',
  22: 'Neige forte',
  30: 'Pluie et neige mêlées faibles',
  31: 'Pluie et neige mêlées modérées',
  32: 'Pluie et neige mêlées fortes',
  40: 'Averses de pluie locales et faibles',
  41: 'Averses de pluie locales',
  42: 'Averses locales et fortes',
  43: 'Averses de pluie faibles',
  44: 'Averses de pluie',
  45: 'Averses de pluie fortes',
  46: 'Averses de pluie faibles et fréquentes',
  47: 'Averses de pluie fréquentes',
  48: 'Averses de pluie fortes et fréquentes',
  60: 'Averses de neige localisées et faibles',
  61: 'Averses de neige localisées',
  62: 'Averses de neige localisées et fortes',
  63: 'Averses de neige faibles',
  64: 'Averses de neige',
  65: 'Averses de neige fortes',
  66: 'Averses de neige faibles et fréquentes',
  67: 'Averses de neige fréquentes',
  68: 'Averses de neige fortes et fréquentes',
  70: 'Averses de pluie et neige mêlées localisées et faibles',
  71: 'Averses de pluie et neige mêlées localisées',
  72: 'Averses de pluie et neige mêlées localisées et fortes',
  73: 'Averses de pluie et neige mêlées faibles',
  74: 'Averses de pluie et neige mêlées',
  75: 'Averses de pluie et neige mêlées fortes',
  76: 'Averses de pluie et neige mêlées faibles et nombreuses',
  77: 'Averses de pluie et neige mêlées fréquentes',
  78: 'Averses de pluie et neige mêlées fortes et fréquentes',
  100: 'Orages faibles et locaux',
  101: 'Orages locaux',
  102: 'Orages fort et locaux',
  103: 'Orages faibles',
  104: 'Orages',
  105: 'Orages forts',
  106: 'Orages faibles et fréquents',
  107: 'Orages fréquents',
  108: 'Orages forts et fréquents',
  120: 'Orages faibles et locaux de neige ou grésil',
  121: 'Orages locaux de neige ou grésil',
  122: 'Orages locaux de neige ou grésil',
  123: 'Orages faibles de neige ou grésil',
  124: 'Orages de neige ou grésil',
  125: 'Orages de neige ou grésil',
  126: 'Orages faibles et fréquents de neige ou grésil',
  127: 'Orages fréquents de neige ou grésil',
  128: 'Orages fréquents de neige ou grésil',
  130: 'Orages faibles et locaux de pluie et neige mêlées ou grésil',
  131: 'Orages locaux de pluie et neige mêlées ou grésil',
  132: 'Orages fort et locaux de pluie et neige mêlées ou grésil',
  133: 'Orages faibles de pluie et neige mêlées ou grésil',
  134: 'Orages de pluie et neige mêlées ou grésil',
  135: 'Orages forts de pluie et neige mêlées ou grésil',
  136: 'Orages faibles et fréquents de pluie et neige mêlées ou grésil',
  137: 'Orages fréquents de pluie et neige mêlées ou grésil',
  138: 'Orages forts et fréquents de pluie et neige mêlées ou grésil',
  140: 'Pluies orageuses',
  141: 'Pluie et neige mêlées à caractère orageux',
  142: 'Neige à caractère orageux',
  210: 'Pluie faible intermittente',
  211: 'Pluie modérée intermittente',
  212: 'Pluie forte intermittente',
  220: 'Neige faible intermittente',
  221: 'Neige modérée intermittente',
  222: 'Neige forte intermittente',
  230: 'Pluie et neige mêlées',
  231: 'Pluie et neige mêlées',
  232: 'Pluie et neige mêlées',
  235: 'Averses de grêle',
};

//Table des codes renvoyé par l'api, qui donne une icône associés aux codes des champs weather des objets forecast.
export const WEATHER_ICONS = {
  0: 'wi-day-sunny',
  1: 'wi-day-cloudy',
  2: 'wi-day-cloudy',
  3: 'wi-cloud',
  4: 'wi-cloudy',
  5: 'wi-day-cloudy',
  6: 'wi-day-fog',
  7: 'wi-day-fog',
  10: 'wi-day-showers',
  11: 'wi-day-rain',
  12: 'wi-day-rain',
  13: 'wi-day-showers',
  14: 'wi-day-rain',
  15: 'wi-day-rain',
  16: 'wi-day-showers',
  20: 'wi-day-snow',
  21: 'wi-day-snow',
  22: 'wi-day-snow',
  30: 'wi-day-rain-mix',
  31: 'wi-day-rain-mix',
  32: 'wi-day-rain-mix',
  40: 'wi-rain',
  41: 'wi-rain',
  42: 'wi-rain',
  43: 'wi-rain',
  44: 'wi-rain',
  45: 'wi-rain',
  46: 'wi-rain',
  47: 'wi-rain',
  48: 'wi-rain',
  60: 'wi-snow',
  61: 'wi-snow',
  62: 'wi-snow',
  63: 'wi-snow',
  64: 'wi-snow',
  65: 'wi-snow',
  66: 'wi-snow',
  67: 'wi-snow',
  68: 'wi-snow',
  70: 'wi-rain-mix',
  71: 'wi-rain-mix',
  72: 'wi-rain-mix',
  73: 'wi-rain-mix',
  74: 'wi-rain-mix',
  75: 'wi-rain-mix',
  76: 'wi-rain-mix',
  77: 'wi-rain-mix',
  78: 'wi-rain-mix',
  100: 'wi-day-lightning',
  101: 'wi-day-lightning',
  102: 'wi-day-thunderstorm',
  103: 'wi-day-lightning',
  104: 'wi-day-lightning',
  105: 'wi-day-thunderstorm',
  106: 'wi-day-lightning',
  107: 'wi-day-lightning',
  108: 'wi-day-thunderstrom',
  120: 'wi-day-snow-thunderstorm',
  121: 'wi-day-snow-thunderstorm',
  122: 'wi-day-snow-thunderstorm',
  123: 'wi-day-snow-thunderstorm',
  124: 'wi-day-snow-thunderstorm',
  125: 'wi-day-snow-thunderstorm',
  126: 'wi-day-snow-thunderstorm',
  127: 'wi-day-snow-thunderstorm',
  128: 'wi-day-snow-thunderstorm',
  130: 'wi-day-sleet-storm',
  131: 'wi-day-sleet-storm',
  132: 'wi-day-sleet-storm',
  133: 'wi-day-sleet-storm',
  134: 'wi-day-sleet-storm',
  135: 'wi-day-sleet-storm',
  136: 'wi-day-sleet-storm',
  137: 'wi-day-sleet-storm',
  138: 'wi-day-sleet-storm',
  140: 'wi-day-thunderstorm',
  141: 'wi-day-sleet-storm',
  142: 'wi-day-snow-thunderstorm',
  210: 'wi-day-rain',
  211: 'wi-day-rain',
  212: 'wi-day-rain',
  220: 'wi-day-snow',
  221: 'wi-day-snow',
  222: 'wi-day-snow',
  230: 'wi-day-rain-mix',
  231: 'wi-day-rain-mix',
  232: 'wi-day-rain-mix',
  235: 'wi-day-sleet',
};
